### PR TITLE
Fix Class 'CodeIgniter\Services' not found

### PR DESCRIPTION
**Pull request by kenjis**
Sorry, I forgot to add loading `CodeIgniter\Services` in `index.php`.
But I found that we don't have to load it.

`class_alias()` works fine for our purpose, and the `system/Services.php` file makes IDE auto complete.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Nice solution. I'm not sure exactly how much overhead a class alias provides. I know that it does load the file, but that's perfect in this case.

**Comment by lonnieezell** [comment]
With your latest pull requests integrated, i'm unable to run coverage. Are you getting these issues, too, or do I just have something setup wrong? It's telling me: 

Fatal error: Cannot declare class CodeIgniter\Services, because the name is already in use in /Volumes/MyData/WebSites/CodeIgniter4/Project/system/Services.php on line 10

**Comment by kenjis** [comment]
Probably I did not generate report.

I get the following error in this branch.

> Generating code coverage report in HTML format ...PHP Fatal error:  Declaration of CodeIgniter\Database\MySQLi\Connection::_escapeString($str) must be compatible with CodeIgniter\Database\BaseConnection::_escapeString(string $str): string in .../CodeIgniter4/system/Database/MySQLi/Connection.php on line 7

I get the following error in the latest develop branch:

> PHP Fatal error:  Class CodeIgniter\Database\MockConnection contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\BaseConnection::_listTables, CodeIgniter\Database\BaseConnection::_listColumns) in /.../CodeIgniter4/tests/_support/Database/MockConnection.php on line 3

**Comment by lonnieezell** [comment]
Sorry. Hadn't pushed the latest changes, I guess. They should be live now.

**Comment by kenjis** [comment]
I've got the error. Fix: #58

**Pull request merged**
