### PR TITLE
Improve Config\Services for testing

### PR DESCRIPTION
**Pull request by kenjis**
How about this?

`Confgi\RealServices` is a just copy of `Config\Services` (of course, we have to change only the classname).

We could generate it with a command if we write a script.

### CODE REVIEW

**Comment by lonnieezell** [comment]
I can live with this. My initial thought was that it wasn't crucial since services weren't likely to change much, but that was limiting the thinking to just the framework and not for use in an application. 

Should the script run automatically during test bootstrapping? That's probably overkill, but seems like the best time to ensure it's accurate.

**Comment by vonalbert** [comment]
This will solve the problem of the almost identical Service classes and this is good.
The more I think to this problem, the more I would like to see a base static class.. I'm a silly person, I know :)
However, until we can't find a better solution to centralize core's services copying from the app folder is fine

**Comment by kenjis** [comment]
> My initial thought was that it wasn't crucial since services weren't likely to change much, but that was limiting the thinking to just the framework and not for use in an application.

Yeah, I also didn't think framework users might often change the config.
If they changes often, the script should run automatically during test bootstrapping.
But I don't like the way. It is no simple.

It seems that it might be better we have two files.
1. `Config\Services` is the definitions. It is the same as the current `Config\Services`.
2. But we use, for example, `CodeIgniter\Services` which extends `Config\Services`.
When testing, we use special `CodeIgniter\Services` like the one in this PR.

Or
1. We use `Config\Services` as (for example) `Services` with using `class_alias()`.
2. When testing, we use special `Services` class.
But when we use `class_alias()`, probably IDE can't give the method information.

**Comment by lonnieezell** [comment]
I came here to say that I think we're overcomplicating something that doesn't need to be, but I ended up talking myself out of that, I think. :) 

We use Services in two places during testing, and that's in the bootstrap file, for Exceptions and Autoloader. I was thinking that we could hard code those, and then not worry about it the duplicate file issue, since any unit testing done on an application will be restricted to classes the user creates, and they would responsible for loading the appropriate files. That thinking broke down when I considered any integration testing, and we would like to provide simple integration testing tools into our test suite, so we have to have a working Services class that knows any changes in the application Services file so that integration testing works correctly. 

I think the first option you just gave, @kenjis, is the proper one. It keeps the Services current, allows mocks to be injected as needed, and doesn't have any affect during normal app execution.

**Comment by kenjis** [comment]
See #54

**Pull request closed without merging**
