### PR TITLE
Refactor CodeIgniter.php as a class

### PR DESCRIPTION
**Pull request by kenjis**
The current `CodeIgniter.php` is not a class. It is difficult to reuse and a bit difficult to read.
This PR makes it as a class, and remove `global` variables.

I don't think this is perfect. This is just a beginning.

I think we need to reuse some parts of the code in it in application functional testing.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Let me start by saying I'm not opposed to making this a class. I had considered it myself, but hadn't come up with a really valid reason to make the change, since I don't fall in the class of developers that says that when we embrace OOP, that *everything* must suddenly be an object. But I would like some clarification on a couple of things. 

First off - **what is the need to reuse the code that happens in this script?** This is executed once per request. Period. CodeIgniter doesn't, and never has, natively supported HMVC. Even then, doing HMVC with the current code shouldn't pose a problem that I can think of, since there's no global object that might be instantiated twice. The Services layer class takes care of a lot of that, so the Request and Response classes used by the controller can easily be accessed in both controllers. 

You say it might need to be called in application functional testing, but isn't that type of testing typically done by the test suites by essentially creating a headless browser that loads the pages and observes the results? 

There are some items that seem a bit pointless to store as class parameters, namely the route-related stuff, like current controller, method, etc. That will be used in one function, and if others need it, they would be called from that method. Any testing that routes happen properly happen through the unit testing, correct? 

What's the purpose of replacing a single line call with a method call? I understand it keeps the symmetry in the `exec()` method, but are there any other purposes? I'm talking about lines like `require_once BASEPATH . 'Common.php';`, `require APPPATH . 'Config/Services.php';`, and `require_once BASEPATH . 'Common.php';`. There's no need for these to be functions as that just provides additional overhead that is unneeded. Simply require them at the top of the file or method and call it good.

The one thing that really needed help for readability wasn't touched here. :) That's the `startController()` method.

**Comment by lonnieezell** [comment]
After reading through issue #31, I'll go ahead and merge this change for now, but will address my concerns and push a new commit tonight with the concerns addressed.

**Comment by kenjis** [comment]
Yeah, the CodeIgniter class is not really good OOP. I just converted `CodeIgniter.php` to a class mechanically. So please refactor it as you like.

> You say it might need to be called in application functional testing, but isn't that type of testing typically done by the test suites by essentially creating a headless browser that loads the pages and observes the results? 

Functional testing, I mean, is testing like this: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-to-controller

We send emulated requests and get the results.

> What's the purpose of replacing a single line call with a method call? I understand it keeps the symmetry in the exec() method, but are there any other purposes?

It does not have any special purposes. I just made a method for a block.
So please change as you like.

**Comment by lonnieezell** [comment]
> Functional testing, I mean, is testing like this: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-to-controller

> We send emulated requests and get the results.

That looks great. I look forward to having those methods as part of our testing suite. :)

**Comment by ivantcholakov** [comment]
I suppose, it makes sense also if we are capable to extend this class and modify how the framework loads itself.

**Comment by lonnieezell** [comment]
> I suppose, it makes sense also if we are capable to extend this class and modify how the framework loads itself.

I'm not sure I agree with that. It's easy enough to do that right now - create a new class that modifies the boot process to your needs, then modify index.php to load that class instead. That doesn't require any additional overhead or complexity in the boot process than what it already has. And if you need to modify the boot process more than Hooks provide, you're outside the design parameters of the framework anyway.

**Comment by kenjis** [comment]
@ivantcholakov It is easy now as @lonnieezell  says.

**Pull request merged**
