### PR TITLE
Replacing hard coded file paths with class reflection file paths

### PR DESCRIPTION
**Pull request by sv3tli0**
I suggest this reflection way to get class filepaths instead of hard coding file start paths which should be moved.

### CODE REVIEW

**Comment by lonnieezell** [comment]
It's a good idea. My first instinct was that CI's autoloader would conflict but then realized this would only run during a Composer process so we should be fine.

**Comment by avenirer** [comment]
Sorry... I haven't followed the evolution of CI4 for a long time... am I to understand that it will use components from other parts (Zend Escaper)?

**Comment by lonnieezell** [comment]
Very few, and they will be packaged as part of the download so Composer not needed. Zend Escaper is the only one currently included this way, and that's because it is the best library out there, written by some of the most knowledgable people on the topic. 

Other than that, we're currently bundling in the Kint debug tool.

**Comment by avenirer** [comment]
ok. thank you.

**Comment by sv3tli0** [comment]
Shouldn't be a problem for CI Autoloader while this one is only started by composer post script.

I am not quite sure but I think that such file move should not exists at all. Instead CI Autoloader can detect if the Zend Escaper class exists on its try to load it at first place. And in case it exists (coming from the composer vendor) use it as it is. 

The one which is inside the system folder should be working as a backup if there is no vendor zend escaper. 

And because its not logical to have Zend/Escaper/Escaper class inside CodeIgniter_system/View folder perhaps there should be some 3rd party folder inside CI system to put there anything that CI needs to run correctly. But its usage should be only if its not already loaded either by composer or other way.

**Comment by lonnieezell** [comment]
The reason this is done in the first place is because the community demands a download and go package, no Composer needed. :) 

This is basically a way for the team to easily ensure the download packages have an up to date version of the file. For those who download the zip file and go from there, the files wouldn't exist unless we bundle it, so we can't rely on it being in vendor folder, or that a vendor folder even exists. 

While I like the idea of keeping it in a third-party folder, we're trying to make it so that each group of libraries can be used as standalone packages in your own projects. That's why this was originally included here, to group it with the functionality it belongs with. I suppose, though, that in that case, the user would likely be using Composer, anyway, so it could just be a dependency...

**Pull request merged**
